import Database from "better-sqlite3";
const dbPath = "C:/Users/cellu/AppData/Roaming/Beholden/beholden.db";
const db = new Database(dbPath, { readonly: true });
const row = db.prepare("SELECT character_data_json FROM user_characters WHERE id = ?").get("b59d5eb8-9441-499d-bdcc-52b5185ae650");
const data = JSON.parse(row.character_data_json);
console.log("chosenCantrips:", JSON.stringify(data.chosenCantrips));
console.log("chosenSpells:", JSON.stringify(data.chosenSpells));
console.log("preparedSpells:", JSON.stringify(data.preparedSpells));
console.log("classes:", JSON.stringify(data.classes));
db.close();
