import { theme } from "@/theme/theme";
import { Button } from "@/ui/Button";
import { Input } from "@/ui/Input";
import { SpellChoiceMenu } from "./SpellFormControls";
import { togglePillStyle } from "./browserParts";
import { AMMO_FAMILIES, ITEM_MODIFIER_TARGETS, WEAPON_MASTERIES, type ItemFormData } from "./ItemFormModel";
import { ItemColumn, ItemEmpty, ItemField, ItemPills, itemChoices, itemRemoveStyle, itemSectionStyle, itemSectionTitle, type ItemFormSetter } from "./ItemFormCommon";

const modifierTargetOptions = [{ value: "", label: "None" }, ...ITEM_MODIFIER_TARGETS.map((value) => ({
  value,
  label: value.split("_").map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(" "),
}))];
const weaponProperties = [
  ["A", "Ammunition"], ["BF", "Burst Fire"], ["F", "Finesse"], ["H", "Heavy"],
  ["L", "Light"], ["LD", "Loading"], ["M", "Martial"], ["R", "Reach"],
  ["RC", "Reload"], ["S", "Special"], ["T", "Thrown"], ["V", "Versatile"], ["2H", "Two-Handed"],
] as const;

export function ItemMechanicsView({ form, set }: { form: ItemFormData; set: ItemFormSetter }) {
  const hasSpecific = form.isWeapon || form.isArmor;
  return <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(360px,.8fr)", gap: 12, alignItems: "start" }}>
    <ItemColumn>{form.isWeapon ? <WeaponSection form={form} set={set} /> : null}{form.isArmor ? <ArmorSection form={form} set={set} /> : null}{!hasSpecific ? <section style={itemSectionStyle}><h3 style={itemSectionTitle}>Type-specific mechanics</h3><ItemEmpty>This item has no weapon or armor mechanics enabled. You can enable them from Basics.</ItemEmpty></section> : null}<UsesSection form={form} set={set} /></ItemColumn>
    <ItemColumn><ModifiersSection form={form} set={set} /><RollsSection form={form} set={set} /></ItemColumn>
  </div>;
}

function WeaponSection({ form, set }: { form: ItemFormData; set: ItemFormSetter }) {
  const selected = form.properties.split(",").map((value) => value.trim()).filter(Boolean);
  const toggleProperty = (code: string) => set("properties", (selected.includes(code) ? selected.filter((value) => value !== code) : [...selected, code]).join(", "));
  return <section style={itemSectionStyle}><h3 style={itemSectionTitle}>Weapon</h3><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10 }}><ItemField label="Base weapon / proficiency"><Input value={form.proficiency} onChange={(e) => set("proficiency", e.target.value)} placeholder="martial, longsword" /></ItemField><ItemField label="Damage"><Input value={form.damage} onChange={(e) => set("damage", e.target.value)} placeholder="1d8" /></ItemField><ItemField label="Versatile damage (two-handed)"><Input value={form.twoHandedDamage} onChange={(e) => set("twoHandedDamage", e.target.value)} placeholder="Optional, e.g. 1d10" /></ItemField><ItemField label="Damage type"><Input value={form.damageType} onChange={(e) => set("damageType", e.target.value)} placeholder="Slashing" /></ItemField><ItemField label="Range"><Input value={form.range} onChange={(e) => set("range", e.target.value)} placeholder="20/60" /></ItemField><ItemField label="Mastery"><SpellChoiceMenu ariaLabel="Weapon mastery" value={form.mastery} onChange={(value) => set("mastery", value)} options={itemChoices(WEAPON_MASTERIES)} /></ItemField><ItemField label="Ammunition family"><SpellChoiceMenu ariaLabel="Weapon ammunition" value={form.weaponAmmo} onChange={(value) => set("weaponAmmo", value)} options={itemChoices(AMMO_FAMILIES)} /></ItemField></div><div style={{ color: theme.colors.muted, fontSize: "var(--fs-tiny)", marginTop: 8 }}>Leave versatile damage blank when the weapon has no alternate two-handed damage die.</div><div style={{ color: theme.colors.muted, fontSize: "var(--fs-small)", fontWeight: 700, marginTop: 12 }}>Properties</div><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 6 }}>{weaponProperties.map(([code, label]) => <button key={code} type="button" style={togglePillStyle(selected.includes(code))} onClick={() => toggleProperty(code)}>{label}</button>)}</div></section>;
}
function ArmorSection({ form, set }: { form: ItemFormData; set: ItemFormSetter }) { const shield = form.type === "Shield"; return <section style={itemSectionStyle}><h3 style={itemSectionTitle}>Armor</h3><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><ItemField label={shield ? "AC bonus" : "Armor AC"}><Input type="number" min={0} value={form.armorAc} onChange={(e) => set("armorAc", e.target.value)} placeholder={shield ? "2" : "11"} /></ItemField><ItemField label="Strength requirement"><Input type="number" min={0} value={form.armorStrength} onChange={(e) => set("armorStrength", e.target.value)} /></ItemField></div><div style={{ color: theme.colors.muted, fontSize: "var(--fs-tiny)", marginTop: 8 }}>{shield ? "The amount this shield adds to AC." : "The AC printed for this armor: for example, Leather Armor is 11 and Chain Mail is 16. Put a magical +1 in Passive Modifiers instead."}</div><ItemPills items={[{ label: "Stealth disadvantage", active: form.stealthDisadvantage, toggle: () => set("stealthDisadvantage", !form.stealthDisadvantage) }]} /></section>; }
function UsesSection({ form, set }: { form: ItemFormData; set: ItemFormSetter }) { return <section style={itemSectionStyle}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><h3 style={itemSectionTitle}>Charges and uses</h3><ItemPills items={[{ label: "Has uses", active: form.usesEnabled, toggle: () => set("usesEnabled", !form.usesEnabled) }]} /></div>{form.usesEnabled ? <><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><ItemField label="Maximum"><Input value={form.usesMax} onChange={(e) => set("usesMax", e.target.value)} placeholder="10 or 1d6+1" /></ItemField><ItemField label="Long-rest recovery"><Input value={form.usesRecover} onChange={(e) => set("usesRecover", e.target.value)} placeholder="1d6+4; blank restores all" /></ItemField></div><div style={{ color: theme.colors.muted, fontSize: "var(--fs-tiny)", marginTop: 8 }}>Automatically rolled and applied when the character completes a Long Rest. Leave blank to restore all charges.</div></> : <ItemEmpty>No charge pool.</ItemEmpty>}</section>; }
function ModifiersSection({ form, set }: { form: ItemFormData; set: ItemFormSetter }) { return <section style={itemSectionStyle}><div style={{ display: "flex", justifyContent: "space-between" }}><div><h3 style={itemSectionTitle}>Passive modifiers</h3><div style={{ color: theme.colors.muted, fontSize: "var(--fs-tiny)", margin: "-5px 0 9px" }}>These are signed bonuses or penalties applied while the item is active. An amount of 1 means +1; -1 means −1.</div></div><Button type="button" variant="ghost" onClick={() => set("modifiers", [...form.modifiers, { target: "ac", amount: "1" }])}>+ Modifier</Button></div>{form.modifiers.map((row, index) => <div key={index} style={{ display: "grid", gridTemplateColumns: "1fr 110px 30px", gap: 6, marginBottom: 6 }}><SpellChoiceMenu ariaLabel="Modifier target" value={row.target} onChange={(value) => set("modifiers", form.modifiers.map((entry, i) => i === index ? { ...entry, target: value } : entry))} options={modifierTargetOptions} /><Input aria-label="Modifier amount" title="Signed bonus or penalty" type="number" value={row.amount} onChange={(e) => set("modifiers", form.modifiers.map((entry, i) => i === index ? { ...entry, amount: e.target.value } : entry))} placeholder="+1" /><button type="button" style={itemRemoveStyle} onClick={() => set("modifiers", form.modifiers.filter((_, i) => i !== index))}>×</button></div>)}{!form.modifiers.length ? <ItemEmpty>No passive modifiers.</ItemEmpty> : null}</section>; }
function RollsSection({ form, set }: { form: ItemFormData; set: ItemFormSetter }) { return <section style={itemSectionStyle}><div style={{ display: "flex", justifyContent: "space-between" }}><h3 style={itemSectionTitle}>Rolls</h3><Button type="button" variant="ghost" onClick={() => set("rolls", [...form.rolls, { formula: "", description: "" }])}>+ Roll</Button></div>{form.rolls.map((row, index) => <div key={index} style={{ display: "grid", gridTemplateColumns: "130px 1fr 30px", gap: 6, marginBottom: 6 }}><Input value={row.formula} onChange={(e) => set("rolls", form.rolls.map((entry, i) => i === index ? { ...entry, formula: e.target.value } : entry))} placeholder="1d6+1" /><Input value={row.description} onChange={(e) => set("rolls", form.rolls.map((entry, i) => i === index ? { ...entry, description: e.target.value } : entry))} placeholder="Description" /><button type="button" style={itemRemoveStyle} onClick={() => set("rolls", form.rolls.filter((_, i) => i !== index))}>×</button></div>)}{!form.rolls.length ? <ItemEmpty>No structured rolls.</ItemEmpty> : null}<div style={{ color: theme.colors.muted, fontSize: "var(--fs-tiny)", marginTop: 6 }}>Rolls describe item dice such as healing, damage, or recharge.</div></section>; }
