import { theme } from "@/theme/theme";
import { Input } from "@/ui/Input";
import { useSpellSearch } from "@/views/CompendiumView/hooks/useSpellSearch";
import { SpellChoiceMenu } from "./SpellFormControls";
import type { ItemFormData, ItemSpellRow } from "./ItemFormModel";
import { ItemEmpty, ItemField, ItemPills, itemRemoveStyle, itemSectionStyle, itemSectionTitle, type ItemFormSetter } from "./ItemFormCommon";

export function ItemSpellsView({ form, set }: { form: ItemFormData; set: ItemFormSetter }) {
  const { q, setQ, rows, busy } = useSpellSearch();
  const selected = new Set(form.spells.map((spell) => spell.id));
  const results = rows.filter((row) => !selected.has(row.id)).slice(0, 12);
  const update = (index: number, patch: Partial<ItemSpellRow>) => set("spells", form.spells.map((row, i) => i === index ? { ...row, ...patch } : row));
  return <div style={{ display: "grid", gridTemplateColumns: "minmax(360px,.72fr) minmax(0,1fr)", gap: 12, alignItems: "start" }}>
    <section style={itemSectionStyle}><h3 style={itemSectionTitle}>Add spells</h3><div style={{ color: theme.colors.muted, fontSize: "var(--fs-small)", lineHeight: 1.5, marginBottom: 10 }}>Search by name. The creator stores the canonical spell reference, so no one needs to know its ID.</div><Input autoFocus value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search spells…" /><div style={{ border: `1px solid ${theme.colors.panelBorder}`, borderRadius: 8, marginTop: 6, maxHeight: 420, overflowY: "auto" }}>{busy ? <ItemEmpty>Loading…</ItemEmpty> : results.map((spell) => <button key={spell.id} type="button" onClick={() => set("spells", [...form.spells, { id: spell.id, name: spell.name, cost: "0", level: "", uses: "", consume: false, maxLevel: "", maxCost: "", upcast: "", dc: "", attack: "", note: "" }])} style={{ display: "flex", justifyContent: "space-between", width: "100%", padding: "9px 10px", border: 0, borderBottom: `1px solid ${theme.colors.panelBorder}`, background: "transparent", color: theme.colors.text, cursor: "pointer" }}><span>{spell.name}</span><span style={{ color: theme.colors.muted }}>{spell.level === 0 ? "Cantrip" : `Level ${spell.level ?? "?"}`} &nbsp; <strong style={{ color: theme.colors.accentPrimary }}>+ Add</strong></span></button>)}{!busy && !results.length ? <ItemEmpty>No matching spells.</ItemEmpty> : null}</div></section>
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}><section style={itemSectionStyle}><h3 style={itemSectionTitle}>Casting rules</h3><ItemField label="Spellcasting numbers"><SpellChoiceMenu ariaLabel="Spellcasting numbers" value={form.spellcasting} onChange={(value) => set("spellcasting", value as ItemFormData["spellcasting"])} options={[{ value: "", label: "Not specified" }, { value: "character", label: "Use character's spellcasting" }, { value: "fixed", label: "Fixed DC / attack bonus" }]} /></ItemField>{form.spellcasting === "fixed" ? <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 8 }}><ItemField label="Save DC"><Input type="number" min={0} value={form.spellDc} onChange={(e) => set("spellDc", e.target.value)} /></ItemField><ItemField label="Attack bonus"><Input type="number" value={form.spellAttack} onChange={(e) => set("spellAttack", e.target.value)} /></ItemField></div> : null}</section>
      <section style={itemSectionStyle}><h3 style={itemSectionTitle}>Granted spells · {form.spells.length}</h3><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{form.spells.map((spell, index) => <div key={spell.id} style={{ border: `1px solid ${theme.colors.panelBorder}`, borderRadius: 9, padding: 9 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" }}><strong>{spell.name ?? spell.id}</strong><button type="button" style={itemRemoveStyle} onClick={() => set("spells", form.spells.filter((_, i) => i !== index))}>×</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 6, marginTop: 7 }}><ItemField label="Charge cost"><Input value={spell.cost} onChange={(e) => update(index, { cost: e.target.value })} placeholder="0 or level" /></ItemField><ItemField label="Cast level"><Input type="number" min={0} max={9} value={spell.level} onChange={(e) => update(index, { level: e.target.value })} /></ItemField><ItemField label="Own uses"><Input value={spell.uses} onChange={(e) => update(index, { uses: e.target.value })} /></ItemField><ItemField label="Max level"><Input type="number" min={0} max={9} value={spell.maxLevel} onChange={(e) => update(index, { maxLevel: e.target.value })} /></ItemField><ItemField label="Max cost"><Input type="number" min={0} value={spell.maxCost} onChange={(e) => update(index, { maxCost: e.target.value })} /></ItemField><ItemField label="Upcast / charge"><Input type="number" min={1} value={spell.upcast} onChange={(e) => update(index, { upcast: e.target.value })} /></ItemField><ItemField label="DC override"><Input type="number" min={0} value={spell.dc} onChange={(e) => update(index, { dc: e.target.value })} /></ItemField><ItemField label="Attack override"><Input type="number" value={spell.attack} onChange={(e) => update(index, { attack: e.target.value })} /></ItemField></div><ItemPills items={[{ label: "Consumes item", active: spell.consume, toggle: () => update(index, { consume: !spell.consume }) }]} /><Input value={spell.note} onChange={(e) => update(index, { note: e.target.value })} placeholder="Optional casting note" style={{ marginTop: 7 }} /></div>)}</div>{!form.spells.length ? <ItemEmpty>No spells selected.</ItemEmpty> : null}</section></div>
  </div>;
}
