export type SpellCheck = "attack" | "str" | "dex" | "con" | "int" | "wis" | "cha";
export type SpellEffect = "acid" | "bludgeoning" | "cold" | "fire" | "force" | "lightning" | "necrotic" | "piercing" | "poison" | "psychic" | "radiant" | "slashing" | "thunder" | "healing" | "temp_hp";
type SpellRollForm = { formula: string; effects: SpellEffect[]; description: string; level: string };
export type SpellForEdit = { id: string; ruleset?: "5e" | "5.5e"; name: string; source?: string; level?: number | null; school?: string | null; casting?: { time?: string; range?: string; components?: { verbal?: true; somatic?: true; material?: true | string }; duration?: { description?: string; concentration?: true } }; ritual?: true; access?: string[]; check?: SpellCheck; rolls?: Array<{ formula: string; effect?: SpellEffect | SpellEffect[]; description?: string; level?: number }>; description: string[]; [key: string]: unknown };
export type SpellFormData = { name: string; ruleset: "5e" | "5.5e"; source: string; level: string; school: string; time: string; range: string; duration: string; concentration: boolean; ritual: boolean; verbal: boolean; somatic: boolean; material: boolean; materialText: string; access: string[]; check: SpellCheck | ""; rolls: SpellRollForm[]; text: string };

export const SCHOOLS = ["Abjuration", "Conjuration", "Divination", "Enchantment", "Evocation", "Illusion", "Necromancy", "Transmutation"] as const;
export const CHECK_OPTIONS: Array<{ value: SpellCheck; label: string }> = [{ value: "attack", label: "Spell attack" }, { value: "str", label: "STR save" }, { value: "dex", label: "DEX save" }, { value: "con", label: "CON save" }, { value: "int", label: "INT save" }, { value: "wis", label: "WIS save" }, { value: "cha", label: "CHA save" }];
export const EFFECT_OPTIONS: SpellEffect[] = ["acid", "bludgeoning", "cold", "fire", "force", "lightning", "necrotic", "piercing", "poison", "psychic", "radiant", "slashing", "thunder", "healing", "temp_hp"];
const ACCESS_IDS = ["sl_artificer","sl_artificer_alchemist","sl_artificer_armorer","sl_artificer_artillerist","sl_artificer_battle_smith","sl_artificer_cartographer","sl_bard","sl_cleric","sl_cleric_knowledge_domain","sl_cleric_life_domain","sl_cleric_light_domain","sl_cleric_trickery_domain","sl_cleric_war_domain","sl_druid","sl_druid_circle_of_the_land_arid","sl_druid_circle_of_the_land_polar","sl_druid_circle_of_the_land_temperate","sl_druid_circle_of_the_land_tropical","sl_druid_circle_of_the_moon","sl_druid_circle_of_the_sea","sl_paladin","sl_paladin_oath_of_devotion","sl_paladin_oath_of_glory","sl_paladin_oath_of_the_ancients","sl_paladin_oath_of_the_noble_genies","sl_paladin_oath_of_vengeance","sl_ranger","sl_ranger_fey_wanderer","sl_ranger_gloom_stalker","sl_ranger_winter_walker","sl_sorcerer","sl_sorcerer_aberrant_sorcery","sl_sorcerer_clockwork_sorcery","sl_sorcerer_draconic_sorcery","sl_sorcerer_spellfire_sorcery","sl_warlock","sl_warlock_archfey_patron","sl_warlock_celestial_patron","sl_warlock_fiend_patron","sl_warlock_great_old_one_patron","sl_wizard"];
const title = (value: string) => value.split("_").map((word) => word === "of" || word === "the" ? word : word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
export const ACCESS_OPTIONS = ACCESS_IDS.map((id) => ({ id, label: title(id.slice(3)) }));

export function emptySpellForm(): SpellFormData { return { name: "", ruleset: "5.5e", source: "", level: "", school: "", time: "", range: "", duration: "", concentration: false, ritual: false, verbal: false, somatic: false, material: false, materialText: "", access: [], check: "", rolls: [], text: "" }; }
export function spellToForm(spell: SpellForEdit): SpellFormData { const material = spell.casting?.components?.material; return { name: spell.name ?? "", ruleset: spell.ruleset === "5e" ? "5e" : "5.5e", source: spell.source ?? "", level: spell.level == null ? "" : String(spell.level), school: spell.school ?? "", time: spell.casting?.time ?? "", range: spell.casting?.range ?? "", duration: spell.casting?.duration?.description ?? "", concentration: spell.casting?.duration?.concentration === true, ritual: spell.ritual === true, verbal: spell.casting?.components?.verbal === true, somatic: spell.casting?.components?.somatic === true, material: material != null, materialText: typeof material === "string" ? material : "", access: spell.access ?? [], check: spell.check ?? "", rolls: (spell.rolls ?? []).map((roll) => ({ formula: roll.formula, effects: roll.effect == null ? [] : Array.isArray(roll.effect) ? roll.effect : [roll.effect], description: roll.description ?? "", level: roll.level == null ? "" : String(roll.level) })), text: (spell.description ?? []).join("\n\n") }; }
export function buildSpellPayload(form: SpellFormData, original: SpellForEdit | null): Record<string, unknown> { if (!form.name.trim()) throw new Error("Name is required."); const description = form.text.split(/\n\s*\n/u).map((part) => part.trim()).filter(Boolean); if (!description.length) throw new Error("Description is required."); const level = form.level === "" ? undefined : Number(form.level); if (level != null && (!Number.isInteger(level) || level < 0 || level > 9)) throw new Error("Level must be from 0 to 9."); const components = { ...(form.verbal ? { verbal: true as const } : {}), ...(form.somatic ? { somatic: true as const } : {}), ...(form.material ? { material: form.materialText.trim() || true } : {}) }; const duration = { ...(form.duration.trim() ? { description: form.duration.trim() } : {}), ...(form.concentration ? { concentration: true as const } : {}) }; const casting = { ...(form.time.trim() ? { time: form.time.trim() } : {}), ...(form.range.trim() ? { range: form.range.trim() } : {}), ...(Object.keys(components).length ? { components } : {}), ...(Object.keys(duration).length ? { duration } : {}) }; const rolls = form.rolls.map((roll, index) => { if (!roll.formula.trim()) throw new Error(`Roll ${index + 1} needs a formula.`); if (roll.effects.length > 1 && roll.effects.some((effect) => effect === "healing" || effect === "temp_hp")) throw new Error(`Roll ${index + 1} cannot combine healing or temporary HP with other effects.`); const rollLevel = roll.level === "" ? undefined : Number(roll.level); if (rollLevel != null && (!Number.isInteger(rollLevel) || rollLevel < 0 || rollLevel > 20)) throw new Error(`Roll ${index + 1} level must be from 0 to 20.`); return { formula: roll.formula.trim(), ...(roll.effects.length === 1 ? { effect: roll.effects[0] } : roll.effects.length > 1 ? { effect: roll.effects } : {}), ...(roll.description.trim() ? { description: roll.description.trim() } : {}), ...(rollLevel != null ? { level: rollLevel } : {}) }; }); const payload: Record<string, unknown> = { ...(original ?? {}), ruleset: form.ruleset, name: form.name.trim(), description }; const optional = (key: string, value: unknown) => { payload[key] = value; }; optional("source", form.source.trim() || undefined); optional("level", level); optional("school", form.school || undefined); optional("casting", Object.keys(casting).length ? casting : undefined); optional("ritual", form.ritual ? true : undefined); optional("access", form.access.length ? form.access : undefined); optional("check", form.check || undefined); optional("rolls", rolls.length ? rolls : undefined); return payload; }
