import { useUiMessages, useUiTranslation } from "@beholden/shared/i18n/useUiTranslation";
import React from "react";
import { Input, theme, useSpellSearch } from "./ItemEditorHost";
import { SpellChoiceMenu } from "./SpellFormControls";
import type { ItemFormData, ItemSpellRow } from "./ItemFormModel";
import { ItemEmpty, ItemField, ItemPills, itemRemoveStyle, itemSectionStyle, itemSectionTitle, type ItemFormSetter } from "./ItemFormCommon";

export function ItemSpellsView({ form, set }: { form: ItemFormData; set: ItemFormSetter }) {
  const translateMessage = useUiMessages("sharedUi");
  const translateUi = useUiTranslation("sharedUi");
  const { q, setQ, rows, busy, rulesetFilter, setRulesetFilter } = useSpellSearch();
  // The item's own ruleset is the implicit ruleset for spells it grants -- names are stored
  // at add-time (below), so this only needs to scope the search picker, not a live lookup.
  React.useEffect(() => {
    if (rulesetFilter !== form.ruleset) setRulesetFilter(form.ruleset);
  }, [form.ruleset, rulesetFilter, setRulesetFilter]);
  const selected = new Set(form.spells.map((spell) => spell.id));
  const results = rows.filter((row) => !selected.has(row.id)).slice(0, 12);
  const update = (index: number, patch: Partial<ItemSpellRow>) => set("spells", form.spells.map((row, i) => i === index ? { ...row, ...patch } : row));
  return <div style={{ display: "grid", gridTemplateColumns: "minmax(360px,.72fr) minmax(0,1fr)", gap: 12, alignItems: "start" }}>
    <section style={itemSectionStyle}><h3 style={itemSectionTitle}>{translateUi("Add spells")}</h3><div style={{ color: theme.colors.muted, fontSize: "var(--fs-small)", lineHeight: 1.5, marginBottom: 10 }}>{translateUi("Search by name. The creator stores the canonical spell reference, so no one needs to know its ID.")}</div><Input autoFocus value={q} onChange={(e) => setQ(e.target.value)} placeholder={translateUi("Search spells…")} /><div style={{ border: `1px solid ${theme.colors.panelBorder}`, borderRadius: 8, marginTop: 6, maxHeight: 420, overflowY: "auto" }}>{busy ? <ItemEmpty>{translateUi("Loading…")}</ItemEmpty> : results.map((spell) => <button key={spell.id} type="button" onClick={() => set("spells", [...form.spells, { id: spell.id, name: spell.name, cost: "0", level: "", uses: "", consume: false, maxLevel: "", maxCost: "", upcast: "", dc: "", attack: "", note: "" }])} style={{ display: "flex", justifyContent: "space-between", width: "100%", padding: "9px 10px", border: 0, borderBottom: `1px solid ${theme.colors.panelBorder}`, background: "transparent", color: theme.colors.text, cursor: "pointer" }}><span>{spell.name}</span><span style={{ color: theme.colors.muted }}>{spell.level === 0 ? translateUi("Cantrip") : translateUi("Level {{value1}}", { value1: spell.level ?? "?" })} &nbsp; <strong style={{ color: theme.colors.accentPrimary }}>{translateUi("+ Add")}</strong></span></button>)}{!busy && !results.length ? <ItemEmpty>{translateUi("No matching spells.")}</ItemEmpty> : null}</div></section>
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}><section style={itemSectionStyle}><h3 style={itemSectionTitle}>{translateUi("Casting rules")}</h3><ItemField label={translateUi("Spellcasting numbers")}><SpellChoiceMenu ariaLabel={translateMessage("Spellcasting numbers")} value={form.spellcasting} onChange={(value) => set("spellcasting", value as ItemFormData["spellcasting"])} options={[{ value: "", label: translateUi("Not specified") }, { value: "character", label: translateUi("Use character's spellcasting") }, { value: "fixed", label: translateUi("Fixed DC / attack bonus") }]} /></ItemField>{form.spellcasting === "fixed" ? <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 8 }}><ItemField label={translateUi("Save DC")}><Input type="number" min={0} value={form.spellDc} onChange={(e) => set("spellDc", e.target.value)} /></ItemField><ItemField label={translateUi("Attack bonus")}><Input type="number" value={form.spellAttack} onChange={(e) => set("spellAttack", e.target.value)} /></ItemField></div> : null}</section>
      <section style={itemSectionStyle}><h3 style={itemSectionTitle}>{translateUi("Granted spells ·")} {form.spells.length}</h3><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{form.spells.map((spell, index) => <div key={spell.id} style={{ border: `1px solid ${theme.colors.panelBorder}`, borderRadius: 9, padding: 9 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" }}><strong>{spell.name ?? spell.id}</strong><button type="button" style={itemRemoveStyle} onClick={() => set("spells", form.spells.filter((_, i) => i !== index))}>×</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 6, marginTop: 7 }}><ItemField label={translateUi("Charge cost")}><Input value={spell.cost} onChange={(e) => update(index, { cost: e.target.value })} placeholder={translateUi("0 or level")} /></ItemField><ItemField label={translateUi("Cast level")}><Input type="number" min={0} max={9} value={spell.level} onChange={(e) => update(index, { level: e.target.value })} /></ItemField><ItemField label={translateUi("Own uses")}><Input value={spell.uses} onChange={(e) => update(index, { uses: e.target.value })} /></ItemField><ItemField label={translateUi("Max level")}><Input type="number" min={0} max={9} value={spell.maxLevel} onChange={(e) => update(index, { maxLevel: e.target.value })} /></ItemField><ItemField label={translateUi("Max cost")}><Input type="number" min={0} value={spell.maxCost} onChange={(e) => update(index, { maxCost: e.target.value })} /></ItemField><ItemField label={translateUi("Upcast / charge")}><Input type="number" min={1} value={spell.upcast} onChange={(e) => update(index, { upcast: e.target.value })} /></ItemField><ItemField label={translateUi("DC override")}><Input type="number" min={0} value={spell.dc} onChange={(e) => update(index, { dc: e.target.value })} /></ItemField><ItemField label={translateUi("Attack override")}><Input type="number" value={spell.attack} onChange={(e) => update(index, { attack: e.target.value })} /></ItemField></div><ItemPills items={[{ label: translateUi("Consumes item"), active: spell.consume, toggle: () => update(index, { consume: !spell.consume }) }]} /><Input value={spell.note} onChange={(e) => update(index, { note: e.target.value })} placeholder={translateUi("Optional casting note")} style={{ marginTop: 7 }} /></div>)}</div>{!form.spells.length ? <ItemEmpty>{translateUi("No spells selected.")}</ItemEmpty> : null}</section></div>
  </div>;
}
